language: go

go:
- 1.9
before_install:
install:
- go get github.com/tools/godep
- go get github.com/clipperhouse/{linkedlist,set,slice,stringer,typewriter}
- go get -t github.com/yinqiwen/gsnova/remote/server github.com/yinqiwen/gsnova/local/client
script:
- cd remote/server && godep save && tar cf ../../tmp-deploy.tar * .godir && cd ../.. && tar uf tmp-deploy.tar server.json && bzip2 tmp-deploy.tar && mv tmp-deploy.tar.bz2 gsnova-paas-deploy-with-dependencies-${TRAVIS_TAG}.tar.bz2
- export CGO_ENABLED=0
- GOOS=windows GOARCH=386 go build -o gsnova_client.exe github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_windows_386-${TRAVIS_TAG}.tar.bz2 client.json hosts.json gsnova_client.exe
- GOOS=windows GOARCH=amd64 go build -o gsnova_client.exe github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_windows_amd64-${TRAVIS_TAG}.tar.bz2 client.json hosts.json gsnova_client.exe
- GOOS=linux GOARCH=386 go build -o gsnova_client github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_linux_386-${TRAVIS_TAG}.tar.bz2 client.json hosts.json gsnova_client
- GOOS=linux GOARCH=amd64 go build -o gsnova_client github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_linux_amd64-${TRAVIS_TAG}.tar.bz2 client.json hosts.json gsnova_client
- GOOS=linux GOARCH=arm go build -o gsnova_client github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_linux_arm-${TRAVIS_TAG}.tar.bz2 client.json hosts.json gsnova_client
- GOOS=darwin GOARCH=amd64 go build -o gsnova_client github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_macos_amd64-${TRAVIS_TAG}.tar.bz2 client.json hosts.json gsnova_client
- GOOS=linux GOARCH=386 go build -o gsnova_server github.com/yinqiwen/gsnova/remote/server
- tar cjf gsnova_server_linux_386-${TRAVIS_TAG}.tar.bz2 server.json gsnova_server
- GOOS=linux GOARCH=amd64 go build -o gsnova_server github.com/yinqiwen/gsnova/remote/server
- tar cjf gsnova_server_linux_amd64-${TRAVIS_TAG}.tar.bz2 server.json gsnova_server



deploy:
  provider: releases
  api_key:
    secure: YngDT2JlydCG+qb8Ww9wBFyWiLRQJczybNLeoFKluBXKoh1Vu+TZeReMK+rRUjOqOmYV8sNtOnEVSg4+ICeYDNp9fRRwcNKTkp0H+8pH0OynxdH2faCjx1H5U0WQuWqMLQoMSHZ90I0tL40kEJOChLY6WGvwY47YBqi/dsvmTfg=
  file: 
    - "gsnova-paas-deploy-with-dependencies-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_windows_386-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_windows_amd64-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_linux_386-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_linux_amd64-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_linux_arm-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_macos_amd64-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_server_linux_amd64-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_server_linux_386-${TRAVIS_TAG}.tar.bz2"
  skip_cleanup: true
  on:
    tags: true
    repo: yinqiwen/gsnova
